---
mode: required
method: legacy
default: limine

labels:
  step: "Boot"

items:
  - id: limine
    name: "Limine"
    description: "Modern BIOS and UEFI boot with LuigiOS Btrfs snapshot integration."
    screenshot: "/etc/calamares/images/bootloaders/limine.jxl"
