---
efiSystemPartition: "/boot"
efiSystemPartitionSize: 4096M
userSwapChoices: [ none ]
luksGeneration: luks2
drawNestedPartitions: false
alwaysShowPartitionLabels: true
initialPartitioningChoice: none
initialSwapChoice: none
defaultFileSystemType: "btrfs"
defaultPartitionTableType: gpt
availableFileSystemTypes: [ "btrfs" ]
enableLuksAutomatedPartitioning: true

bootloaderOverrides:
  - name: limine
    defaultFileSystemType: "btrfs"
    availableFileSystemTypes: [ "btrfs" ]
    efiSystemPartition: "/boot"
    efiSystemPartitionSize: 4096M
    luksGeneration: luks2
    initialSwapChoice: none
    initialPartitioningChoice: none
