---
dontChroot: true

script:
  - "mkdir -p ${ROOT}/etc/pacman.d"
  - "cp /etc/pacman.d/mirrorlist ${ROOT}/etc/pacman.d/"
  - "cp /etc/pacman.d/cachyos-mirrorlist ${ROOT}/etc/pacman.d/"
  - "cp /etc/pacman.d/cachyos-v3-mirrorlist ${ROOT}/etc/pacman.d/"
  - "cp -a /etc/pacman.d/gnupg ${ROOT}/etc/pacman.d/"
  - "cp /etc/resolv.conf ${ROOT}/etc/"

i18n:
  name: "Initialize the pinned LuigiOS package source"
