---
dontChroot: false
timeout: 300

script:
  - command: "/etc/calamares/scripts/btrfs-installation-snapshot"
    verbose: true
  - "-rm /etc/calamares/scripts/btrfs-installation-snapshot"

i18n:
  name: "Creating the permanent LuigiOS restore point"
