Window.SetBackgroundTopColor(0.0, 0.0, 0.0);
Window.SetBackgroundBottomColor(0.0, 0.0, 0.0);

logo.image = Image("logo.png");
logo.sprite = Sprite(logo.image);
logo.sprite.SetX(Window.GetWidth() / 2 - logo.image.GetWidth() / 2);
logo.sprite.SetY(Window.GetHeight() / 2 - logo.image.GetHeight() / 2 - 24);

progress.image = Image.Text("LUIGIOS", 0.133, 0.773, 0.369, 1.0,
                            "Inter", 14, "center");
progress.sprite = Sprite(progress.image);
progress.sprite.SetX(Window.GetWidth() / 2 - progress.image.GetWidth() / 2);
progress.sprite.SetY(Window.GetHeight() / 2 + logo.image.GetHeight() / 2 + 8);

fun refresh_callback () {
    progress.sprite.SetOpacity(0.58 + 0.30 * Math.Sin(Plymouth.GetTime() * 2.4));
}
Plymouth.SetRefreshFunction(refresh_callback);

fun message_callback (text) {
    message.image = Image.Text(text, 0.79, 0.82, 0.85, 1.0,
                               "Inter", 12, "center");
    message.sprite = Sprite(message.image);
    message.sprite.SetX(Window.GetWidth() / 2 - message.image.GetWidth() / 2);
    message.sprite.SetY(Window.GetHeight() * 0.78);
}
Plymouth.SetMessageFunction(message_callback);
